### ISSUE TITLE
add Xvfb launch to runtime

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#122]
@landmanbester this is for you. Things like ``casaplotms`` want an X11 display even if they don't need one. There may be other tools that sneakily connect to X11, so better to have an Xvfb running in the background at all times to work around this.

**Comment by o-smirnov** [comment]
Speaking of which, @landmanbester I think I saw a notification on my phone this morning where you reminded me on this, but now I can't find mention in the Kubernauts space. Where/how did you send the message?

**Comment by landmanbester** [comment]
Just pinged you on the same thread, used your sarao account by mistake

**Comment by o-smirnov** [comment]
Actually @landmanbester  this may be a trivial fix. There's a wrapper called ``xvfb-run`` that does the job for us. So just add

```
casa: xvfb-run -a casa
```

to your cab definition for casaplotms, and it might be all you need. I pushed a small fix to ``issue-126`` to support this (it needs to split the casa string into multiple arguments for this to work).

**Comment by landmanbester** [comment]
I am not sure I follow. Do you mean to define a cab like so?
```
casa.plotms:
    command: plotms
    flavour: casa-task
    casa: xvfb-run -a casa
    inputs:
      _include: casa/plotms.yaml
```
Or where do I add that bit?

**Comment by o-smirnov** [comment]
Yep exactly.

Cheers,
Oleg

--

**Comment by landmanbester** [comment]
I get the following error if I try that
```
2023-01-13 15:44:43 STIMELA ERROR: error applying configuration from triA.yaml: Key 'casa' not in 'Cab'
    full_key: cabs.casa.plotms.casa
    reference_type=Cab
    object_type=Cab
```
This is on the issue-126 branch

**Comment by o-smirnov** [comment]
Yeah sorry, misleading you. Try:

```yml
casa.plotms:
    command: plotms
    flavour: 
      kind: casa-task
      casa: xvfb-run -a casa
    inputs:
      _include: casa/plotms.yaml
```

**Comment by landmanbester** [comment]
Hooray! That works. Thanks

**Comment by o-smirnov** [comment]
All right, closing this, as we don't seem to need a "centralized" solution in the code itself.

**Comment by o-smirnov** [comment]
Reopening this, as it's probably useful to do this centrally for all casa-flavour tasks.

**Comment by o-smirnov** [comment]
Perhaps I can add something like
```yml
flavour:
  kind: casa-task
  path: /path/to/casa # optional
  wrapper: xvfb-run -a
```
With ``xvfb-run -a`` being the default setting for wrapper?
