### ISSUE TITLE
restructure wsclean outputs

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#128]
Really an issue for ``cult-cargo``, but marking it here for now.

Wsclean output names are a mess, just because there's so many of them. Since we now support nested inputs/outputs, use this feature to impose some order. Still a WIP, but something along these lines:

```yml
outputs:
  dirty:
    per-band:
      dtype: List[File]
    mfs:
      dtype: FIle
    mfs-stokes:
      i:
        dtype: File
      q:
        dtype: File
# etc etc
```

We can retain the "legacy" names for now, to ease the transition from old recipes.
