### ISSUE TITLE
better status display for for-loops

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#129]
Current display status when running a for loop is ``[N/M]``.

Looping over scans in my Jove reduction, I like to see the scan name too, so e.g. ``[scan=11 2/4]``.

This can be supported by an optional ``display_status`` field under ``for_loop``. If not given, use ``[N/M]``. Otherwise, specify a {}-format string, so e.g. the above can be accomplished by

```yml
  for_loop:
    var: scan
    over: scan-list
    display_status: "{var}={value} {index1}/{total}"
```
