### ISSUE TITLE
add variable assignment based on another variable

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#13]
I want to be able to set things based on e.g. the name of the MS, or the band, or whatever. So I'm thinking (at recipe level)

```yml
assign_via_mapping:
  ms:
    msname1:
      var1: value1
      var2: value2
    msname2:
      var1: value3
      var2: value4
    DEFAULT:
      var1: value5
      var2: value6
```
