### ISSUE TITLE
add top-level default-recipe key

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#132]
Useful when multiple recipes are defined. E.g. I have ``jove-pol-loop.yml`` which does

```yml
_include: 
  - jove-pol.yml
# ...
jove-pol-loop: # a for-loop invoking jove-pol
```

``jove-pol.yml`` is a recipe that's runnabe by itself (for a single scan). If I include it into the loop recipe, I end up with two top-level recipes, and I now have to specify one to run explicitly. Having a ``default-recipe: jove-pol-loop`` entry in the loop recipe file eliminates that annoyance.
