### ISSUE TITLE
add shorthand schema option

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#134]
```yml
inputs:
  foo: 
    dtype: int
  bar:
    dtype: str
    default: baz
```
should also be (quite Pythonically) specifiable as
```yml
inputs:
  foo: int
  bar: str = baz
```
As an extra advantage, one could then just copy-and-paste Python signatures i.e.
```python
def func(foo: int, bar: str = "baz"):
```
becomes simply
``` yml
inputs: { foo: int, bar: str = "baz" }
```
in the cab definition.

**Comment by o-smirnov** [comment]
Noting that help strings (the ``info`` field) can be included as

```yml
inputs:
  foo: int "this is an int parameter"
  bar: str = baz "this is a string"

```

**Comment by o-smirnov** [comment]
Note also that the ``required`` property can be accommodated by this syntax:

```yml
inputs:
  foo: int * "this is a required int parameter"
  bar: str = baz "this is a string"
```

Can use some other character to indicate, but I like ``*``, since it is commonly recognized as an indicator of required information (e.g. think of any web form you've ever filled).
