### ISSUE TITLE
Referencing step parameters from a sub-recipe

### ISSUE THREAD

**Issue by SpheMakh** [caracal-pipeline/stimela2#14]
At the moment I'm using the OmegaConf relative reference mechanism (see `simulate_obs.recipe.inputs.label`)

```yaml
simobs:
  info: Makes a set of simulated MK+ measurement given a list of MK+ antennas to add to the MeerKAT layout. Returns a list of measurement sets for a given parameter set (Dec, synthesis time, nchan, etc.).
  inputs:
    label:
      dtype: str
      default: mkext12
      choices: "${oc.dict.keys: vars.sequence}"
    outdir:
      dtype: Directory
      default: ${vars.indir}
  steps:
    make_layout:
      cab: make_layout
      params:
        name: "{recipe.outdir}/{recipe.label}.itrf.txt"
        layout-label: "{recipe.label}"
    simulate_obs:
      params:
        layout: "{previous.layout}"
        label: "{previous.layout-label}"
      recipe:
        inputs:
          label:
            dtype: str
            default: ${...params.label}  # <<<<<<<<<<<<<<
```

I think tracking heritage would fix this. Then we could do

```yaml
      recipe:
        inputs:
          label:
            dtype: str
            default: "{recipe.parent.inputs.layout-label}"  # <<<<<<<<<<<<<<
```
