### ISSUE TITLE
add port forwarding to kube backend

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#165]
Got this from @JSKenyon: ``kubectl port-forward service/dj-5d0dbd2c-scheduler 8787:http-dashboard`` forwards the dashboard.

Maybe we can save the user this trouble, and add an optional ``port_fowarding`` section to the kube backend options.

**Comment by o-smirnov** [comment]
@JSKenyon @landmanbester this is implemented this on the ``FIASCO3`` branch. Set as follows:

```yml
backend:
  kube:
    dask_cluster:
        forward_dashboard_port: 8787
```

Default is enabled, port 8787. Set to 0 to disable.
