### ISSUE TITLE
how to provision temporary storage to a recipe

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#167]
In case of the native backend, this is straightforward. For the kube backend, it's more subtle. See also https://github.com/ratt-ru/kubernauts/issues/76

Might be worthwhile to think about abstracting this somehow. A recipe property that tells stimela, "this recipe uses X Gb of temporary storage":

* The native backend doesn't need to do anything with this info -- but perhaps check for available disk space and issue a warning. 

* The kube backend will need to provision storage (see https://github.com/ratt-ru/kubernauts/issues/76), and clean it up when the recipe exists (or falls over)

**Comment by o-smirnov** [comment]
Mostly done. Specified in the kube backend options like so (note changes/extensions to ``volumes`` section):

```yml
      volumes:
        rarg-test-compute-efs-pvc:   # mounts a persistent volume from an existing PVC
          mount: /mnt/data

        fsx-dev-scratch:                       # ditto
          capacity: 1000Gi                    # ...but will check that capacity is sufficient
          mount: /scratch

        ebs-temp1:                               # provisions a temporary volume
          storage_class_name: rarg-test-compute-ebs-sc-immediate
          capacity: 10Gi
          lifecycle: session                   # 'session' means volume will be released when recipe is done
          mount: /temp1

        ebs-temp2:                               # ditto
          storage_class_name: rarg-test-compute-ebs-sc-immediate
          capacity: 10Gi
          lifecycle: session
          mount: /temp2
```

Note that this can also be specified in the backend options at cab/step level. ``lifecycle: step`` can be used to make the volume transient for that step only.
