### ISSUE TITLE
misleading prevalidation error message when a substitution is unknown

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#170]
See e.g. a  step like this:

```yml
    fft-image-5res:
      cab: fft-image
      params:
        image: =steps.res-image-*.dirty.vv
        fft-image: =STRIPEXT(current.image) + ".fft.fits"
        lambda-per-arcsec: 100
```

``image`` is not valid (should be ``dirty.v`` not ``dirty.vv``) -- but the error actually thrown comes from ``STRIPEXT()``, and looks misleading, try to make it more sensible.
