### ISSUE TITLE
Support substitutions in backend config

### ISSUE THREAD

**Issue by JSKenyon** [caracal-pipeline/stimela2#190]
It would be very powerful if Stimela could support substitutions in the backend config. This would be particularly useful for benchmarking software as we could potentially do something like:
```yaml
_include:
  - kubeconfig.yaml
  - (cultcargo)quartical.yml

opts:
  backend:
    select: kube

1gc:
  name: CROSSCAL

  for_loop:
    var: nnodes
    over: [1,2,3,4]

  inputs:
    nnodes:  # Not sure if this even needs to be defined as an input.
      dtype: int
      default: 1

  steps:
    gkb1:
      cab: quartical
      backend:
        kube:
          job_pod:
            type: thin
            memory:
              limit: 6Gi
            cpu:
              limit: 1
          dask_cluster:
            name: qc-test-cluster
            num_workers: =recipe.nnodes
            threads_per_worker: 1
            worker_pod:
              type: fat
              cpu:
                limit: =recipe.nnodes
              memory:
                  limit: "55Gi"
      params:
        dask.workers: =recipe.nnodes
```
This example would simply run the same experiment with different node setups. At present, this has to be configured by hand.
