### ISSUE TITLE
balooning RAM usage when running a long for-loop

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#195]
As noted by @Athanaseus.

```
ssh ramaila@crosby
cd working
source ../.virtualenvs/stimela_fiasco/bin/activate
stimela -C run /home/ramaila/working/image_products.yml --step de-sources-only-0 de-mask=/home/ramaila/working/mask/PictorA_1-MFS-hotspot-6144-mask.image.fits upsample-model-channels=1024 dir-out-base=caracal-output-0 ms=/home/ramaila/working/msdir/PicA-PictorA-corr.ms
```

Due to a bug in the profiling stats accumulation, and a poor futures use pattern.

**Comment by o-smirnov** [comment]
@Athanaseus try the ``issue-195`` branch (which I've checked out on your behalf). Looks fixed to me!

**Comment by Athanaseus** [comment]
Thanks @o-smirnov, this worked seamlessly.

```
im_products:
  elapsed: 2039.167659
  avg:
    cpu: 53.60552890478905
    mem_used: 16.4190584600374
    mem_total: 504.0
    load: 45.538216928205784
    read_count: 7581.293235222376
    read_gb: 0.03581490397637468
    read_gbps: 0.30520211950158543
    read_ms: 3095.7738840556144
    write_count: 171.1127327424994
    write_gb: 0.06810173576212926
    write_gbps: 0.541799385636849
    write_ms: 4384.862956337914
    num_samples: 1.0
  peak:
    cpu: 100.0
    mem_used: 37
    mem_total: 504
    load: 83.49
    read_count: 138633739
    read_gb: 652.788140296936
    read_gbps: 2.1208502569628647
    read_ms: 66013728
    write_count: 2993818
    write_gb: 1191.2661781311035
    write_gbps: 8.126115406236455
    write_ms: 70236063
    num_samples: 1
```
