### ISSUE TITLE
assign_based_on not working correctly in a for loop

### ISSUE THREAD

**Issue by landmanbester** [caracal-pipeline/stimela2#199]
The following recipe
```yaml
cabs:
  print_inputs:
    flavour: python-code
    command: |
      print(ms)
      print(out)

    inputs:
      ms:
        dtype: str
        required: true
      out:
        dtype: str
        required: true

init_loop:
  info: xds initialisation loop

  assign_based_on:
    obs:
      F001:
        ms: test1
        out: out1

      F002:
        ms: test2
        out: out2

  for_loop:
    var: obs
    over: [F001, F002]

  inputs:
    input1:
      dtype: int
      default: 1
    input2:
      dtype: int
      default: 2

  steps:
    test:
      cab: print_inputs
      params:
        ms: =recipe.ms
        out: =recipe.out
```
falls over with
```
init_loop.assign_based_on: 'obs' is not a known variable
```
I think ```assign_based_on``` is evaluated before the loop is triggered so ```obs``` doesn't exist yet. Adding an ```assign:  obs: F001``` at the recipe level can be used as a workaround
