### ISSUE TITLE
logfiles not separated properly by for-loop iteration

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#217]
As reported in https://github.com/caracal-pipeline/stimela/discussions/216. Need to get the iteration number etc. in there.

**Comment by o-smirnov** [comment]
@Athanaseus, I have added a top-level fix for this. Instead of assigning to the logfile name at step level, just put this into your global options:

```yml
opts:
  log:
    dir: logs/log-{config.run.datetime}
    name: log-{info.taskname}
```

Seemed easier to just add a new symbol called ``info.taskname``, which is set to recipe.iteration.step (as opposed to ``info.fqname``, which is set to just recipe.step). For non-loop recipes, taskname is the same as fqname.
