### ISSUE TITLE
 `Optional[List[str]]` field with `element_choices` fails when left empty (`None`)

### ISSUE THREAD

**Issue by JSKenyon** [caracal-pipeline/stimela2#242]
When attempting to test the latest version of `stimela` with `quartical` I ran into the following:
```
⚠ pre-validation of recipe '1gc' failed
└── step 'gkb1' failed prevalidation
    └── 1gc.gkb1.output.products: invalid list element 'None'
```

Recipe was as follows:
```yaml
_include:
  - (cultcargo)quartical.yml

1gc:
  name: gaincal
  info: Basic stimela test

  steps:
    gkb1:
      cab: quartical
      info: Solve for a complex gain.
      params:
        input_ms.path: 'file:///home/jonathan/Reductions/3C147/msdir/C147_unflagged.MS'
        input_model.recipe: 'MODEL_DATA'
        output.gain_directory: 'gaindir/gkb1.qc'
        output.log_directory: 'logdir/logs.qc'
        output.overwrite: true
        output.products:
        output.columns:
        dask.threads: 14
        solver.terms: ['G']
        G.type: diag_complex
```

Note that it gets past this step if I set `output.columns=[]`. It gets stuck elsewhere - more on that in a separate issue.
