### ISSUE TITLE
For-loops and step level assignments fail prevalidation

### ISSUE THREAD

**Issue by JSKenyon** [caracal-pipeline/stimela2#282]
As discussed, when adding a simple for loop to my recipe, I ran into the following error.
```
────────────────────────────────── detailed error report follows ───────────────────────────────────
        ⚠ pre-validation of recipe '1gc' failed                                                     
        └── ValidationError: Value 'Unresolved(recipe.nnodes)' of type 'scabha.basetypes.UNSET'     
            could not be converted to Integer                                                       
                full_key: opts.backend.kube.dask_cluster.num_workers                                
                reference_type=Optional[DaskCluster]                                                
                object_type=DaskCluster  
```
This seems to stem from using the loop variable inside a step level assignment. The following is a stripped-down config which demonstrates the currently bugged pattern. 
```yaml
_include:
  - kubeconfig.yaml
  - (cultcargo)quartical.yml

1gc:
  name: CROSSCAL

  for_loop:
    var: nnodes
    over: [1,2,3]

  steps:
    gkb1:
      cab: quartical
      assign:
        config.opts.backend.kube.dask_cluster.num_workers: =recipe.nnodes
```

The current workaround (courtesy of @o-smirnov) is to first do a dummy assignment at the recipe level as follows:
```yaml
_include:
  - kubeconfig.yaml
  - (cultcargo)quartical.yml

1gc:
  name: CROSSCAL

  assign:
    nnodes: 0

  for_loop:
    var: nnodes
    over: [1,2,3]

  steps:
    gkb1:
      cab: quartical
      assign:
        config.opts.backend.kube.dask_cluster.num_workers: =recipe.nnodes
```
