### ISSUE TITLE
nested =-formulas not properly evaluated when invoked via {}-substitutions

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#293]
This doesn't work right. Formula itself gets baked into the string.
```yml
        outdir: =STRIPEXT(recipe.cds) + ".lightcurves"
        regfile: "{current.outdir/lc.reg}"
        statsfile: "{current.outdir/lc.stats.p}"
```
This workaround does:
```yml
        outdir: =STRIPEXT(recipe.cds) + ".lightcurves"
        regfile: =current.outdir + "/lc.reg"
        statsfile: =current.outdir + "/lc.stats.p"
```
