### ISSUE TITLE
it would be nice to have a for-loop recipe output that is a list of per-iteration outputs from a particular step

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#294]
Quite possibly this can be done via the current aliasing mechanism. As things stand, the current aliased outputs will return the output value from the last iteration. But a flag could be provided in the schema to change that.

**Comment by o-smirnov** [comment]
The question is, should it be an explicit flag, or some magic syntax in the aliases specification? E.g.:

```yml
  outputs:
    loop-list-output:
      aliases: [step.output]
      collect_list_output: true
```
vs

```yml
  outputs:
    loop-list-output:
      aliases: [step.output@]
```
The latter is somewhat more esoteric, but has the advantage of also being compatible with the standalone aliases section.
