### ISSUE TITLE
substitutions in step params sometimes evaluated out of order

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#320]
This should work:
```yml
step:
  params:
    x: =SOME_FORMULA
    y: =current.x + ".fits"
```
...because ``x`` is evaluated before ``y``. Due to a subtle bug, sometimes it doesn't.
