### ISSUE TITLE
Missing parameter error for non-required outputs

### ISSUE THREAD

**Issue by SpheMakh** [caracal-pipeline/stimela2#324]
An output defined as below raises an *invalid parameter* if the parameter is not set

```yaml
outputs:
   temp-dir:
     dtype: Directory
     skip_freshness_checks: true
     mkdir: true
     must_exist: false
     required: false
```

```bash
STIMELA.selfcal-multi INFO:   image_one.temp-dir = Unresolved(temp-dir)                                                                                                                                       
STIMELA.selfcal-multi INFO:   image_two.temp-dir = Unresolved(temp-dir)                                                                                                                                       
STIMELA.selfcal-multi ERROR: step 'selfcal-multi': invalid inputs: 'image_one.temp-dir', 'image_two.temp-dir'
```
