### ISSUE TITLE
Feature request: add option to ignore unknown assignments 

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#336]
Use case (from TRON) -- we have ``tron-oservation-sets.yml`` specifying a whole bunch of options for observations, bands, etc. This is included into the ``tron`` recipe via

```yml
  assign_based_on:
    _include: tron-observation-sets.yml[optional,warn]
```

I would like to reuse some of these settings in a smaller recipe, but this doesn't define all the inputs of ``tron``, so including the same file throws "unknown assignment" errors.

Suggest a sensible workaround would be:

```yml
  assign_based_on:
     _ignore_unknown_assignments: true  
    _include: tron-observation-sets.yml[optional,warn]
```

Which would require the assign logic to recognize the `` _ignore_unknown_assignments`` key and disable errors.
