### ISSUE TITLE
Should assign_based_on assignments be "weak"? 

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#337]
Again from TRON etc. If we have:

```yml
assign_based_on:
  obs:
    L2:
       ms: foo
       stokes: [I,Q,U,V]
       band: L
  band:
    L:
      stokes: [I]
```

we end up with ``stokes=[I]``, since the ``band`` section is evaluated after the ``obs`` section. This prevents us from making per-observation tweaks that override the per-band assignments. Arguably, this is the wrong way around!

A simple solution would be to define ``assign_based_on`` as being a "weak" assignment, i.e. have the assignment take effect only if not already assigned to previously. Thoughts?
