### ISSUE TITLE
Allow for loops over input variables

### ISSUE THREAD

**Issue by landmanbester** [caracal-pipeline/stimela2#358]
In my opinion the following should be allowed
```yaml
test:
  for_loop:
    var: stokes
    over: [I, Q, U, V]
  
  inputs:
    stokes:
      dtype: str
      default: I
      choices: [I, Q, U, V]

  steps:
    step1:
      cab: cab1
      params:
        stokes: =recipe.stokes

cabs:
  cab1:
    flavour: python-code
    backend:
      select: native
    command: |
      print(stokes)
    inputs:
      stokes:
        dtype: str
        required: true
```
It currently falls over with 
```
ERROR: error loading recipe 'test': recipe 'None': for_loop.var=stokes clashes with an input parameter
```
Removing `stokes` from the inputs fixes the problem but it is often the case that we want to loop over one of the inputs so why make this illegal? Consider for example the case in which you want to restrict the choices you can loop over as in the above. Note the `assign: stokes: I` I showed in the meeting no longer seems necessary after merging in the latest changes from `refactor-0.2.0`

**Comment by o-smirnov** [comment]
A for-loop variable that is also an input still makes no sense to me, but I think the construct you're looking for is rather:

```yml
test:
  for_loop:
    var: stokes
    over: stokes-list  # can refer to any input by name here
  
  inputs:
    stokes-list:
      dtype: List[str]
      default: [I]
      element_choices: [I, Q, U, V]
```

Glad to hear the assign is no longer needed, since I do have vague memories of fixing this.
