### ISSUE TITLE
implicitly select the output when defining a Python callable cab with a single output?

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#366]
The confusion [here](https://github.com/caracal-pipeline/stimela/issues/152#issuecomment-2678481902) could be avoided. 

In a case like this:

```yml
flavour:
    kind: python
    output: my_list
outputs:
  my_list:
    dtype: ...
```

i.e. a Python callable cab with a singular output, it may be sensible to just select that output as the implicit destination for the return value, thus obviating the need to specify which output to return it via. 

I hesitate to introduce implicit logic frivolously, but in this case this seems like an intuitively sensible thing to do. Third-party opinions solicited, @JSKenyon @SpheMakh @tmolteno @landmanbester @IanHeywood.
