### ISSUE TITLE
Add =SELECT() function

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#375]
Have ugliness like this on the breifast power spectrum branch:

```yml
    procres:
      cab: breifast.process-residual-cube
      info: processes cube and generates candidate catalog
      params:
        cds: =(recipe.is_raw and recipe.cds) or 
              (recipe.is_convolved and steps.convolve.out-cds) or
              (recipe.is_fd and steps.forward-diff.out-cds) or 
              (recipe.is_ps and steps.power-spectrum.out-cds) or "unsupported timesscale setting {recipe.timescale}"
```

Underlying reason there's a multi-way selection of the input file based on which mode the step is invoked in. This could be simplified by having a built in select function. Something like

```
=SELECT(cond1, result1, 
        cond2, result2, 
         ...)
```

Logic being, evaluate each conditional in turn, and return the first result where the conditional is true, or UNSET if none are true.
