### ISSUE TITLE
add option to bind container directories to different paths

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#377]
This need arose while dealing with https://github.com/caracal-pipeline/cult-cargo/issues/87. It's an example of a more generic need for cabs that depend on external data which may be either auto-downloaded, or perhaps provided in a static version by the system administrator.

Use case: I want to configure the cult-cargo python-astro image to keep the astropy cache in ``/var/cache/astropy``. The cargo images can ensure an up-to-date cache when built. However, I want to provide the user with the option to explicitly refresh the cache (and then use this cache in any other cabs that use astropy). This requires binding a local cache directory (e.g. ``~/.astropy``) to ``/var/cache/astropy`` inside the container.

The current ``backend.singularity.bind_dirs`` syntax implies identical source and target paths, i.e.

```yml
bind_dirs:
  /path: ro
  /other_path: rw
```

Suggest extending this to recognizing

```yml
bind_dirs:
  /path: ro
  /var/cache/astropy: ~/.astropy::rw
```

with the logic being, if the value contains ``::``, treat is as ``path::mode``, otherwise treat it as mode only, and assume the same pathname.

Even more useful would be to recognize {}-substitutions both inside the key and the value (I think only values are currently subject to substitutions), because it will be easier to write this "refresh astropy data" cab more robustly if I could use something like:

```yml
bind_dirs:
  /path: ro
  '{config.vars.cult-cargo.astropy-cache-dir}': '{current.cache-dir}::rw'
```

Easy to implement but any thoughts from @JSKenyon @SpheMakh @sjperkins @landmanbester first?

**Comment by o-smirnov** [comment]
Actually why invent and parse extra syntax, let's just use the normal OmegaConf machinery, and make ``bind_dirs`` a list of mappings:

```yml
bind_dirs:
 - host: /path
   # target: /path  # default target is same as host
   mode: ro   # default is rw
 - host: ~/.astropy
   target: /var/cache/astropy
   mkdir: true  # create host directory if doesn't exist
```

Only slightly more verbose, fewer things to f*ck-up, easier to add attributes such as ``mkdir`` here, and values are all subject to {}-substitution if needed.

**Comment by JSKenyon** [comment]
I definitely prefer the latter suggestion to the former. This seems like a generally useful feature for all applications which require a cache.

**Comment by o-smirnov** [comment]
Then let me make it thus. Another benefit: easy to add a ``conditional`` setting for the bind, since all contents are evaluated.

**Comment by o-smirnov** [comment]
For something like https://github.com/caracal-pipeline/cult-cargo/issues/65, it would also be useful to have a "mount empty temporary directory" option. If the payload needs to write stuff, it can quickly overwhelm the internal container FS. This could be specified as e.g. ``host: empty``. See https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory.

**Comment by o-smirnov** [comment]
Actually, a sequence is not so nice, because it doesn't play well with our merge-and-augment functionality. Suggest rather aribitrary named labels.

```
bind_dirs:
 /path:
   # host: /path   # default is same as section label
   # target: /path  # default target is same as host
   mode: ro   # default is rw

 astropy-cache:
   host: ~/.astropy/cache
   target: /var/cache/astropy
   mkdir: true  # create host directory if doesn't exist
```
