### ISSUE TITLE
mkdir: true on Unresolved directory-type inputs sometimes results in the directory being created anyway

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#409]
With a crazy name like ``Unresolved(foo)``. Need to check for unresolved values before creating directories.

**Comment by o-smirnov** [comment]
@IanHeywood any recollection how you triggered this?

**Comment by IanHeywood** [comment]
Not fully, sorry. It was fixed by changing the definitions in the main yaml from:

```
  assign_based_on:
    _include: solarkat-observation-sets.yaml
```

where they were given as:

```
    dir_out: obs_1696746197_solarkat_split_test
    sun_images_dir: "sun_images"
    regions_dir_out: "region_files"
```

to the main solarkat.yaml itself in the form:

```
    dir_out:
      dtype: Directory
      mkdir: true
    dirty_image_sun_dir:
      dtype: Directory
      default: "{current.dir_out}/dirty_sun_img"
      mkdir: true
    regions_dir_out:
      dtype: Directory
      default: "{current.dir_out}/region_files"
      mkdir: true
```

However it's not the extra `dtype`, `default` and `mkdir` tags that were the solution, as in the original case it was happy to create the main `dir_out` directory but created none of the others. Just to muddy the picture, Victoria's original implementation obviously worked in the past. So it's probably due to one or more of (i) my changes to solarkat; (ii) something weird about the ilifu system; (iii) changes made in the recent version of stimela.
