### ISSUE TITLE
allow sub-recipes to be specified by name

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#41]
I am becoming a little dissatisfied with the current way of incorporating sub-recipes:

```yml
steps:
  foo:
    recipe:
      _use: lib.recipes.subrecipe
```

I want to be able to say simply

```yml
steps:
  foo:
    recipe: subrecipe
```

or

```yml
steps:
  foo:
    recipe: lib.recipes.subrecipe
```

Since OmegaCOnf does not (yet) support unions of containers and primitive types (``recipe: Union[Recipe, str]``), this means declaring ``recipe: Any``, and checking the type at run-time in ``__post_init__``, but we already do that for a bunch of things anyway.
