### ISSUE TITLE
bind_tmp: true does not work with slurm backend

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#418]
The fix in https://github.com/caracal-pipeline/stimela/issues/292 creates slight breakage in slurm.

**Comment by o-smirnov** [comment]
Workaround is to set backend settings as:

```yml
backend:
  singularity:
    bind_tmp: false
```
