### ISSUE TITLE
Should stimela ensure that mounted folders have the expected permissions?

### ISSUE THREAD

**Issue by JSKenyon** [caracal-pipeline/stimela2#439]
Currently, it is possible to mount a read-only Measurement Set as read-write within a container. This does not actually make the Measurement Set writable (which is the correct behaviour), but it can lead to "silent" errors.

Consider the following simple recipe:
```yaml
_include:
  (cultcargo): wsclean.yml

example-recipe:
  name: example-recipe
  info: |
    Image and deconvolve a measurement set, with the intention
    of populating model data.

  inputs:
    ms:
      dtype: MS

  steps:
    test-wsclean:
      cab: wsclean
      params:
        ms: =recipe.ms
        prefix: test
        size: 4096
        scale: "3asec"
        niter: 100
        mgain: 0.999
        save-source-list: true
```
invoked with `stimela run deconvolve.yml ms=test.ms` where `test.ms` has had all write permissions removed using `chmod a-w -R test.ms`.   This will happily run though and produce the following:

![Image](https://github.com/user-attachments/assets/cd722979-1462-4b21-96f9-d7fd81a60dcc)

where the error is reported but effectively ignored. This is problematic as it could lead users to assuming that a step has done something which it has not.

This is, arguably, something which wsclean should check up front (rather than running the entire deconvolution first), but it raises the question of whether stimela should be checking and enforcing the required permissions. The fly in the ointment is that many of our applications have multiple modes and may only require write permission in some modes. I am not sure if there is currently a mechanism for handling this. The "hacky" solution is probably to include a wrangler to turn the above silent error into a real one.

Reported by @Ntsikelelo-Charles.

**Comment by o-smirnov** [comment]
That would not be difficult to check up front. I guess we could even add a field or this to path_policies (``check_permissions``, with a default of true?) so that the check could be disabled in edge cases where it trips us up.

**Comment by JSKenyon** [comment]
> That would not be difficult to check up front. I guess we could even add a field or this to path_policies (`check_permissions`, with a default of true?) so that the check could be disabled in edge cases where it trips us up.

I suspected that checking would be easy. The more irritating issue is likely on the cab definition end. As an example, consider the following from the `wsclean` cab in `cult-cargo`.

```yml
cabs:
  wsclean:
    inputs:
      ms:
        writable: true
        dtype: List[MS]
        required: true
        policies:
          positional: true
          repeat: list
```
This assumes that the input measurement set has to be writable, even though there are modes in which wsclean will not write to the measurement set. We shouldn't make the user experience less pleasant by making this change. As you mentioned, we could add an additional entry to the `path_policies` field, but that will make things which used to work fail (e.g. imaging a read-only MS with no updates to the model column). I guess this has something in common with https://github.com/caracal-pipeline/cult-cargo/issues/132 i.e. it is difficult to reason about the requirements of an input/output when there are so many different modes of operation.
