### ISSUE TITLE
Substitutions not applied to `List` elements

### ISSUE THREAD

**Issue by SpheMakh** [caracal-pipeline/stimela2#44]
For the recipe below, I get the following output

```bash
 foo-dir0 {recipe.label}-dir1  {recipe.label}-dir2
```

Note the substitution is only done for the first run of the `mkdir` cab. The one that specifies a single directory instead of list of directories, the other run does not do the substitution. Is this a bug, or am I missing something?

```yaml
cabs:
  mkdir:
    command: mkdir
    info: mkdir  command

    policies:
      prefix: "--"

    inputs:
      parents:
        dtype: bool
        default: true

    outputs:
      dirs:
        dtype: Union[Directory, List[Directory]]
        policies:
          positional: true
          repeat: repeat

recipe:
  inputs:
    label:
      dtype: str
      default: foo
  steps:
    makedir:
      cab: mkdir
      params:
        dirs: "{recipe.label}-dir0" 
    makedirs:
      cab: mkdir
      params:
        dirs:
         - "{recipe.label}-dir1"
         - "{recipe.label}-dir2"
   ```
