### ISSUE TITLE
Pre- and post- commands should be dictionaries and concatenate commands

### ISSUE THREAD

**Issue by JSKenyon** [caracal-pipeline/stimela2#442]
Currently, the `pre_command` and `post_command` fields only support a single string. This means that user-specified input will overwrite existing values and potentially break specific cabs. 

The solution is to redefine these fields as dictionaries which provide mappings from arbitrary names to Python code strings.

### Current

```yaml
cabs:
  echo:
    flavour:
      kind: python-code
      pre_command: |
        print("foo")
      post_command: |
        print("baz")
    command: |
      print("bar")

    inputs:
      band:
        dtype: str
```

### Suggested
```yaml
cabs:
  echo:
    flavour:
      kind: python-code
      pre_commands:
        echo-foo: |
          print("foo")
      post_commands:
        echo-baz: |
          print("baz")
    command: |
      print("bar")

    inputs:
      band:
        dtype: str
```
