### ISSUE TITLE
custom runners selected by command prefix

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#47]
Thinking of #46, I thought let's have a separate bit of code that

* takes a cab's parameters

* converts them into a command line using this 

    ```yml
    command: casa --nogui --log2term -c 'flagmanager(vis="{current.ms}", mode="{current.mode}", versionname="{current.name}")'
    ```
for inspiration. So then we can have a have a "CASA-flavour" cab which is different from a "normal command cab" in the sense that the command-line is assembled differently (and perhaps failure checking, and post-run cleanup is different). And then for every required CASA task we just define a separate cab where we specify the task name, and the inputs/outputs, and the rest is standard (and uses the same CASA base image).

The I realized we already have a this distinction being made here: https://github.com/caracal-pipeline/stimela2/blob/master/stimela/backends/native.py#L33. We have the normal command cabs, and we have Python callable cabs. The latter is distinguished by ``(module_name)function_name``.

So, I propose we have a general scheme for specifying the flavour via the command string:

```yml
command: command_name       # regulation cab
command: (module)function       # Python callable cab
command: casa::taskname       # CASA-flavour cab 
command: python::(module)function       # alternative syntax for Python callable cab (for consistency)
```

...which also allows for future "flavours"...
