### ISSUE TITLE
throw an error when a parameter schema is empty

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#6]
This mistake:
```yml
inputs:
  foo:
  bar:
    default: 0
```
...parses to ``inputs.foo = None``, which then throws a user-bewildering error at validate.py line 149. 

Not sure how it passes OmegaConf's validation, but we need to add a check for this (i.e. ``None`` schema objects).
