### ISSUE TITLE
Running casa through stimela2

### ISSUE THREAD

**Issue by Kincaidr** [caracal-pipeline/stimela2#64]
Hi,

The general setup for running python scripts in stimela2 is for e.g. as follows:

```yml
  cab_name:
    command: (python_script)python_function
    inputs:
      x1:
        dtype: File
        required: true
      x2:
        dtype: float
    outputs:
      y1:
        dtype: File
```

Where `python_function` is a function existing inside the `(python_script)`. However, If my `(python_script)` contains a casa command how would I set this up?
