### ISSUE TITLE
allow substitution of step.output in implicit recipe outputs

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#66]
If a sub-recipe has implicit outputs linked to a step's output, this should be supported by evaluation. E.g. to have an output conditionally depend on a parameter of the recipe:

```yaml
recipe:
  inputs:
    x:
      ...
  outputs:
    foo:
      implicit: =IF(current.x == "foo", steps.foo.x, steps.bar.x)
```

Currently this doesn't work, because the substitution context of ``foo`` is outside the recipe, in the enclosing step, where the ``steps`` namespace is no longer visible. Perhaps a solution is to retain the ``subst`` namespace returned by the recipe, and to use that for validating the enclosing step's outputs.
