### ISSUE TITLE
Can we have an item variable when using for_loop for labeling the output

### ISSUE THREAD

**Issue by ulricharmel** [caracal-pipeline/stimela2#7]
For example, I am trying to loop over a list of measurements and run cubical but I need a way to label the output directories for each ms.

**Comment by o-smirnov** [comment]
The super quick fix would be to provide a ``{recipe.loop_index}`` substitution in for-loop recipes.

 A more thoughtful solution would perhaps be supporting loops over structured sequences. Something like:

```yml
    my_list_of_jobs:
        - ms: foo.ms
          dir_out: dir1
        - ms: bar.ms
          dir_out: dir2
...
    for_loop:
      var: job
      over: my_list_of_jobs

...
      params:
          ms: '{recipe.job.ms}'
          dir: '{recipe.job.dir_out}'
```
This might already be possible with current substitutions actually.

Even more ninja would be to support indexing within substitutions. The standard Python mechanism knows about ``{some_list[0]}`` and ``{some_dict[foo]}``, but the contents of ``[]`` are treated as a literal number or string.  If we could make it treat it as a variable to be substituted in, then things get even easier.
