### ISSUE TITLE
loop over lines in txt file

### ISSUE THREAD

**Issue by Kincaidr** [caracal-pipeline/stimela2#77]
Hi,

I am trying to use the splitms task built in stimela cab to split scans of an MS into smaller times. I have made a worker that finds the correct times ranges and format for a given interval and outputs them in a txt file like: 
```
2022/02/19/14:47:46.879~2022/02/19/14:57:51.957
2022/02/19/14:57:51.957~2022/02/19/15:07:57.034
```

Using an interval of 3 this 20min scan is broken into intervals of 10 minutes each.

The problem now is how to get stimela to loop over these values so that the splitms task can split according to these timeranges?

Usually, I would write this in python and call it from stimela however; I am using the splitms cab in stimela so will need to do the for-loop in stimela.

I need something like this sub-recipe looping line-by-line over the timeranges in txt file (`timerange_file`) inside a recipe looping over the MS's (`{recipe.ms_list}`):

```
    split_ms_time:
      params:
        timerange_file: {previous.outfile} #where outfile is the txt file of line-by-line timeranges as above
      recipe:
        inputs:
          timerange_file:
            dtype: File
        for_loop:
          var: timerange
          over: timerange_file
      split_ms_by_time:
        cab: splitms_time
        params:
          ms: '{recipe.ms_list}'
          outputvis: '{recipe.dir_out}/{recipe.perscan_dir_out}'
          timerange: '{recipe.outfile}'
          datacolumn: 'all'
```
But what expression can I use in ` timerange_file` for the looping ? `{previous.outfile}` will just give me the txt file.

Any other ideas would also be helpful.

**Comment by o-smirnov** [comment]
Here's a crude hack. Can you rather output a piece of yaml that looks like so. Call it ``timeranges.yml``.

```yaml
timeranges:
  - 2022/02/19/14:47:46.879~2022/02/19/14:57:51.957
  - 2022/02/19/14:57:51.957~2022/02/19/15:07:57.034
```
Then in your recipe.inputs say:

```yaml
inputs:
  _include: timeranges.yml
```

And voila, you have an input called ``timeranges`` that you can give to ``for_loop.over``.

It's slightly less than satisfactory because the setting is static (i.e. you need to generate ``timranges.yml`` before you run the recipe). A proper solution would have to wait for https://github.com/caracal-pipeline/stimela2/issues/78.

**Comment by o-smirnov** [comment]
@Kincaidr if you're brave, try the branch in #91, should give you what you want. Something like

```yml
      cab:
        command: |
          from casacore.tables import table
          tab = table(ms)
          # do stuff
          timeranges = ...
      flavour: python-code
      inputs:
        ms:
          dtype: MS
      outputs:
          timeranges:
            dtype: List[str]
```

...will give you a cab to run a snippet of Python and return results. Inputs and outputs are mapped to/from Python variables.

**Comment by Kincaidr** [comment]
Think I have got it with the previous example; just getting the directory error reported at #83

**Comment by Kincaidr** [comment]
Ok I managed to do this so far by making 3 steps with a for-loop recipe within a main step. Problem now is when I try and input this file:

``` yml
timeranges:
  - 2022/02/19/14:47:46.879~2022/02/19/14:57:51.957
  - 2022/02/19/14:57:51.957~2022/02/19/15:07:57.034
```
Casa reads the actual name like this:

```
# running /usr/bin/casa --nogui --log2term -c split(vis="MIGHTEE_CDFS_raw-J0333_2741-corr_scan_3.ms",                       
outputvis="obs1lb/pertimems.ms", timerange="MIGHTEE_CDFS_raw-J0333_2741-corr_scan_3.ms-time_coordinates.yml", datacolumn="all") --ms MIGHTEE_CDFS_raw-J0333_2741-corr_scan_3.ms --timerange MIGHTEE_CDFS_raw-J0333_2741-corr_scan_3.ms-time_coordinates.yml  --datacolumn all --outputvis obs1lb/pertimems.ms
```

It reads the name `MIGHTEE_CDFS_raw-J0333_2741-corr_scan_3.ms-time_coordinates.yml` not the contents of the yaml I'm trying to loop over.

This is full step:

``` yaml
 split_ms_by_time:
      params:
        scan_list:  =GLOB("*scan*.ms") # =GLOB("*scan*.ms") 
      recipe:
        inputs:
          scan_list:
            dtype: List[MS]
        for_loop:
          var: ms_list
          over: scan_list #[MIGHTEE_CDFS_raw-J0333_2741-corr_scan_3.ms]
        steps:
          perscan_timerange_intervals:
            cab: perscan_timerange_intervals
            params:
              interval: 3 
              scan_list: '{recipe.ms_list}'
              outfile: '{recipe.ms_list}-time_coordinates.yml'
          split_ms_time:
            params:
              timerange_file: '{previous.outfile}' #where outfile is the txt file of line-by-line timeranges
              scan_list: '{recipe.scan_list}'
            recipe:
              inputs:
                timerange_file:
                  dtype: File
                scan_list: 
                  dtype: List[MS]
              for_loop:
                var: timeranges
                over: timerange_file
              steps:  
                split_ms_time:
                  cab: splitms_time
                  params:
                    ms: '{recipe.scan_list}'
                    outputvis: 'obs1lb/pertimems.ms'
                    timerange: '{recipe.timeranges}'
                    datacolumn: 'all'

```
See at end: `timerange: '{recipe.timeranges}'`

There is basically 3 steps: within a main step: `split_ms_by_time`. First 2 steps loop over the scans and get the timerange file as above per ms. 3rd step is a sub-step of these 2 steps to ensure nested for loop. It takes the time range file for that ms and splits it according to the values.

**Comment by o-smirnov** [comment]
Well in the example above ``timerange_file`` is just a single filename, now you're asking it to loop ``timeranges`` over it, so it gives you just one loop with ``timeranges`` set to that filename, which is then passed to CASA which then falls over.

You need to actually read in the timeranges file somehow. So either with ``_include``, or better yet, try as described in https://github.com/caracal-pipeline/stimela2/issues/77#issuecomment-1304772737.

Might as well make the jump -- it also has a much nicer way of defining CASA cabs, see e.g. 
https://github.com/caracal-pipeline/stimela2/blob/relog/tests/stimela_tests/test_casa.yml

**Comment by Kincaidr** [comment]
How would I use for, if, with,etc statements inside a python-code flavour cab? It's not reading them correctly:
``` yaml
split_timeranges:
  command: 
      from pyrap.tables import table
      tb = table(scan_list)
      for i in range(interval):
         ***
      for i in range(len(array)):
        if i < (len(array)-1):
         ***
        else:
         ***
        with open(outfile,'wt') as f:
         ***
    flavour: python-code
      inputs:
        scan_list:
          dtype: MS
        interval:
          dtype: int  
      outputs:
        timeranges:
          dtype: List[str]
```

Same colour as yaml varaibles.

**Comment by o-smirnov** [comment]
You just need to use ``command: |``. That's just YaML syntax for "treat the following indented text as a long multi-line string, until you hit an outer indent level (which would be at 'flavour', in this case)". Without the ``|``, it doesn't know about the continuation lines and it's trying to parse your python code as YaML.

The inputs will come in as Python variables (Stimela will set them up for you), and you can leave the list of timerange strings in a variable called ``timeranges``, Stimela will know to pick it up for the correspondingly-named output. It's really dead simple once you get the syntax right.

Also note ``inputs`` and ``outputs`` should be at the same indentation level as ``flavour``, since they're all cab properties.

Finally, do you know you can now do an "inline cab" directly in a step? I.e. instead of defining the cab separately, you can do a one-off custom cab directly inside the step like so. Useful for quick hacks:

```yml
steps:
  get_timeranges:
    cab:
      command: |
        # some python code
      flavour: python-code
      inputs:
         ...
      outputs:
         ...
    params:
       ....
```

This is all in ``master`` now so may as well start using it fully.

**Comment by Kincaidr** [comment]
For this example:
> 
> ```yaml
> steps:
>   get_timeranges:
>     cab:
>       command: |
>         # some python code
>       flavour: python-code
>       inputs:
>         ms: ' '
>           type: MS
>       outputs:
>         timeranges:
>           type: list[str]
>     params:
>       timeranges: []
>        ms: '{recipe.ms}'
>        ....
> ```

How would I set the parameter timeranges which is a variable from the python-code? 
Usually I would use `'{recipe.}' `or `'{steps.}'` to assign values here but how to do it for a variable in the python-code?

What I keep getting is `timeranges = : value is not a valid list `

**Comment by o-smirnov** [comment]
Take the timeranges out of ``params``. It's an output of the cab, so it doesn't need to be specified. Just have your Python code assign to a Python variable named ``timeranges``, and Stimela will pick it up from there and stick it into ``steps.get_timetranges.timeranges`` (and also ``previous.timeranges`` for the next step). Basically this pattern: https://github.com/caracal-pipeline/stimela2/blob/master/tests/stimela_tests/test_callables.yml#L69

**Comment by Kincaidr** [comment]
Ok finally got this to work:
```
casa --log2term --nologger --nologfile -c import sys, json; split(**json.loads(sys.argv[-1])); {"vis": "obs1lb/perscan_ms/MIGHTEE_CDFS_raw-J0333_2741-corr_scan_14.ms", "timerange": "2022/02/19/14:47:46.879~2022/02/19/14:57:51.957",       
"datacolumn": "DATA"}
```
With:
``` yaml
loop_timeranges:
            params: 
              timeranges: '=previous.timeranges'
              ms: '=previous.scan_list'
            recipe:
              inputs:
                ms: 
                  dtype: MS
                timeranges:
                  dtype: List[str]
              for_loop:
                var: timerange
                over: timeranges
              steps:          
                Casa-split-time:
                  cab: splitms_time
                  params:
                    vis: '{recipe.ms}'
                    timerange: '{recipe.timerange}'
                    outputvis: '{recipe.ms}-output'
                    datacolumn: DATA
```
However, things to note:

1.) So I removed time ranges from the `params` in the cab definition, however, I still needed to define it in the `params` for my for loop like above. Using the `steps.get_timetranges.timeranges` didn't seem to work and kept giving me substitution errors but  `=previous.timeranges` worked.

2.) Ran into a casa error which probably related to #83. I will discuss it further there.
