### ISSUE TITLE
inline Python code in cab command

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/stimela2#82]
As suggested by @SpheMakh at the retreat, this would be useful:

```yaml
cab:
  flavour: python-code
  command: |
    from casacore.tables import table
    tab = table("{current.ms}")
    tab.do_funny_stuff()
  inputs:
    ms: 
      dtype: MS
      required: true
```

Bit of an open question how such code would return outputs. Related to #78.
